# SCALING
TILE_SCALING      = 0.5
CHARACTER_SCALING = int(TILE_SCALING * 2)
SPRITE_PIXEL_SIZE = 128
TILE_PIXEL_SIZE   = int(SPRITE_PIXEL_SIZE * TILE_SCALING)

# WINDOW
SCREEN_WIDTH  = int(TILE_PIXEL_SIZE * 18)
SCREEN_HEIGHT = int(TILE_PIXEL_SIZE * 10)
SCREEN_TITLE  = 'Mephistophelia'

# GAME
GRAVITY               = 1.5
PLAYER_MOVEMENT_SPEED = 10
PLAYER_JUMP_SPEED     = 25
PLAYER_DASH_SPEED     = 25
PLAYER_DASH_DURATION  = 0.1
PLAYER_DASH_COOLDOWN  = 2

PLAY_MODES = ['HUMAN', 'AGENT']
VIEW_MODES = ['ANALYTIC', 'AUTO']

# PLAYER
PLAYER_RIGHT_FACING = 0
PLAYER_LEFT_FACING  = 1

# MAP
MAP_LAYER_GOAL        = 'Goal'
MAP_LAYER_FOREGROUND  = 'Foreground'
MAP_LAYER_PLATFORMS   = 'Platforms'
MAP_LAYER_PLAYER      = 'Player'
MAP_LAYER_BACKGROUND  = 'Background'
MAP_LAYER_DEATHGROUND = 'Deathground'

# AGENT
AGENT_REWARD_DEATH = -int(((TILE_PIXEL_SIZE * 18) / 2))
AGENT_REWARD_GOAL  = int(TILE_PIXEL_SIZE * 18)
AGENT_REWARD_STEP  = -2

AGENT_ACTIONS        = ['LEFT', 'RIGHT', 'JUMP_LEFT', 'JUMP_RIGHT']
AGENT_LEARNING_MODES = ['RANDOM', 'RADAR']
